"""empty message

Revision ID: 86448dffc749
Revises: 
Create Date: 2020-03-16 15:10:23.831711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86448dffc749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ename', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_email'), 'employee', ['email'], unique=True)
    op.create_index(op.f('ix_employee_ename'), 'employee', ['ename'], unique=True)
    op.create_table('items',
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('itemname', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('item_nature', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('itemid')
    )
    op.create_index(op.f('ix_items_itemname'), 'items', ['itemname'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('e_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['e_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.itemid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_items_itemname'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_employee_ename'), table_name='employee')
    op.drop_index(op.f('ix_employee_email'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
