"""empty message

Revision ID: c132037e95ad
Revises: 95e8d1fe55bd
Create Date: 2020-03-18 21:15:21.762852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c132037e95ad'
down_revision = '95e8d1fe55bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_ename', table_name='employee')
    op.create_index(op.f('ix_employee_ename'), 'employee', ['ename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_ename'), table_name='employee')
    op.create_index('ix_employee_ename', 'employee', ['ename'], unique=1)
    # ### end Alembic commands ###
